### ISSUE TITLE
bazel build //.. fails with `invalid repository name '@@'`

### ISSUE THREAD

**Issue by hofbi** [tweag/clodl#54]
**Describe the bug**

**To Reproduce**
- Clone the repo
- Install the requirements
- Run `bazel build //...`

**Expected behavior**
The build passes successfully

**Environment**
 - OS name + version: Ubuntu 20.04
 - Version of the code: Latest master

**Additional context**

```shell
INFO: Analyzed 4 targets (110 packages loaded, 1649 targets configured).
ERROR: ~/clodl/docs/BUILD:4:8: Generating proto for Starlark doc for docs failed: (Exit 1): stardoc failed: error executing Stardoc command (from target //docs:docs) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/io_bazel_stardoc/stardoc/stardoc '--input=@@//clodl:clodl.bzl' '--workspace_name=' '--dep_roots=.' '--dep_roots=external/' ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Exception in thread "main" com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name '@@': workspace names may contain only A-Z, a-z, 0-9, '-', '_' and '.'
        at com.google.devtools.build.lib.cmdline.Label.parseAbsolute(Label.java:149)
        at com.google.devtools.build.lib.cmdline.Label.parseAbsolute(Label.java:106)
        at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:210)
INFO: Elapsed time: 3.997s, Critical Path: 2.63s
INFO: 24 processes: 18 internal, 4 linux-sandbox, 2 worker.
ERROR: Build did NOT complete successfully
```

**Comment by avdv** [comment]
This repository currently works with Bazel 3. It might also work with Bazel 4 and even 5, but 7 is probably not going to work (try to disable bzlmod and try again but here be dragons).

If you just want to try the project, just enter the nix shell and run `bazel build ...`. 

PRs welcome if you figure out how to make it work with more recent Bazel versions / bzlmod. :smile_cat:

**Comment by hofbi** [comment]
I give it a try by migrating to bzlmod
